### PR TITLE
Group membership check

### PR DESCRIPTION
**Pull request by dote78**
Added options to optionally specify a dn for a groupOfNames of which the user has to be a member in order to continue the validation process. Useful if you use the directory to validate in several applications.

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Elgg coding standards require hard tabs (the width of 4 spaces) instead of spaces. Could you change those?

**Comment by dote78** [comment]
Sure, I'll take a look at it. I'm sorry about that. I'm not good at PHP...

**Comment by juho-jaakkola** [comment]
You don't necessarily have to close the PR. If you have access to command line, you can edit existing commits with the `git rebase` command and then push those updated commits into Github.

**Comment by dote78** [comment]
Ouch. I'm also a n00b to github as you can see :sad

**Pull request closed without merging**
